name: 'warehouse_rag_assistant'
version: '1.0.0'
config-version: 2

profile: 'warehouse_rag_assistant'

model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
test-paths: ["dbt/tests"]
analysis-paths: ["dbt/analyses"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  warehouse_rag_assistant:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
